#!/bin/bash

m=$(nmcli d | grep 'ttyUSB4'  | cut -d: -f2| cut -d' ' -f1)

modem=$(echo "/dev/"$m)

echo $modem

sudo pppd $modem 9600 mtu 552 mru 552 modem crtscts dump defaultroute noipdefault ktune noauth logfd 2 logfile /pppd.log lock persist holdoff 2  maxf$

echo "Testing ip"

function valid_ip()
{
    local ip=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1)

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -eq 197 && ${ip[1]} -eq 251 \
            && ${ip[2]} -ge 128 && ${ip[3]} -le 255 ]]	
    fi
}

if [[ "$(basename $0 .sh)" == 'valid_ip' ]]; then

sudo pppd $modem 9600 mtu 552 mru 552 modem crtscts dump defaultroute noipdefault ktune noauth logfd 2 logfile /pppd.log lock persist holdoff 2  maxf$

